# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35936605bc7f15afaf407b92500846b71a57feaad9e22ad4ff38fc4ff8192f5727e3a6f3e85b6e77408f5de27a867e1c8b6f1f669438d9b496d3b62b936939e6

test:
  secret_key_base: a61d378ab46a0aa36efec9fa122d52740519258700790d3c529b43bb255bfb6dfbc9f340160928e2641697043a96be7346625d39e514596c29ab57703ff7a67c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
